#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define GOOGLE_STORAGE_CLIENT_ID_PROP "C_GOOGLE_STORAGE_CLIENT_ID"
#define GOOGLE_STORAGE_EMAIL_ADDRESS_PROP "C_GOOGLE_STORAGE_EMAIL_ADDRESS"
#define GOOGLE_STORAGE_PRIVATE_KEY_PATH_PROP "C_GOOGLE_STORAGE_PRIVATE_KEY_PATH"
#define GOOGLE_STORAGE_BUCKET_NAME_PROP "C_GOOGLE_STORAGE_BUCKET_NAME"
#define GOOGLE_STORAGE_UPLOAD_TYPE_PROP "C_GOOGLE_STORAGE_UPLOAD_TYPE"
#define GOOGLE_STORAGE_CONTENT_TYPE_PROP "C_GOOGLE_STORAGE_CONTENT_TYPE"
#define GOOGLE_STORAGE_CONNECTION_TIMEOUT_PROP "C_GOOGLE_STORAGE_CONNECTION_TIMEOUT"
#define GOOGLE_STORAGE_TIMEOUT_PROP "C_GOOGLE_STORAGE_TIMEOUT"

#define GOOGLE_STORAGE_CLIENT_ID_LEN 256
#define GOOGLE_STORAGE_EMAIL_ADDRESS_LEN 256
#define GOOGLE_STORAGE_PRIVATE_KEY_PATH_LEN 256
#define GOOGLE_STORAGE_BUCKET_NAME_LEN 256
#define GOOGLE_STORAGE_UPLOAD_TYPE_LEN 32
#define GOOGLE_STORAGE_CONTENT_TYPE_LEN 32
#define GOOGLE_STORAGE_CONNECTION_TIMEOUT_LEN 10
#define GOOGLE_STORAGE_TIMEOUT_LEN 10

struct google_storage_props {
  char *client_id;
  char *email_address;
  char *private_key_path;
  char *bucket_name;
  char *upload_type;
  char *content_type;
  char *connection_timeout;
  char *timeout;
};

int get_prop(char *file_path, char *prop, char **value, int max_lenght);
